### ISSUE TITLE
Include the Object type within the returned resolved object?

### ISSUE THREAD

**Issue by burnout87** [oda-hub/oda-resolver#12]
This service is currently used when creating new sources objects in the gallery.

We now want to include the object type as a field for each source, is it possible to extend the resolver service to include such information? Does Simbad return it?

**Comment by volodymyrss** [comment]
yes, it would be useful, good idea. 
we can use the URIs from IVOA like http://www.ivoa.net/rdf/object-type#ae-star 
they match Simbad otype

**Comment by burnout87** [comment]
does the `query_object` call to Simbad returns also the type? because I cannot find that

**Comment by volodymyrss** [comment]
> does the `query_object` call to Simbad returns also the type? because I cannot find that

you have to configure it:

```python
from astroquery.simbad import Simbad

Simbad.remove_votable_fields("otype")
Simbad.add_votable_fields("otype")

result_table = Simbad.query_object("Mrk 421", wildcard=False)
otype = str(result_table[0]['OTYPE']).strip()
```
this should end up in `otype == 'BLLac'`

**Comment by burnout87** [comment]
Just noticed that with the source `Mrk 421` that Simbad returns `BLLac` as object type, whereas on IVOA, this is referenced with the term `bl-lac` (but in the column Label it is actually BLLac).

Is there a way to obtain the term for the IVOA service starting from the Label returned from Simbad?

**Comment by volodymyrss** [comment]
> Just noticed that with the source `Mrk 421` Simbad returns `BLLac` as object type. On IVOA, this is referenced with the term `bl-lac` (but in the column Label it is actually BLLac).
> 
> Is there a way to obtain the term for the IVOA service starting from the Label returned from Simbad?

'BLLac' is its label, check the properties from the ontology:

```turtle
<#bl-lac> a rdfs:Class;
  rdfs:label "BLLac";
  rdfs:comment "BL Lac";
  skos:exactMatch <http://simbad.u-strasbg.fr/simbad/otypes#BLL>;
  ivoasem:preliminary ":__";
  rdfs:subClassOf <#blazar>;
  skos:exactMatch <http://astrothesaurus.org/uat/158>.
```

**Comment by burnout87** [comment]
@volodymyrss  do you know if there is some web service from IVOA that returns the properties from the ontlogy?

**Comment by volodymyrss** [comment]
> @volodymyrss do you know if there is some web service from IVOA that returns the properties from the ontlogy?

I do not know and I seriously doubt it. Please fetch the rdf here https://www.ivoa.net/rdf/object-type/2020-10-06/object-type.ttl and search it with rdflib.
