### ISSUE TITLE
add GW

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/oda-resolver#5]

**Comment by dsavchenko** [comment]
Add with https://github.com/oda-hub/oda-resolver/pull/6

But I wonder how it should be enabled in the frontend, where there is hardcoded url https://github.com/oda-hub/frontend-astrooda/blob/564767c82e08207feb60e7ee5c4020f163ec64bf/astrooda.nameresolver.inc#L4

**Comment by volodymyrss** [comment]
> Add with #6
> 
> But I wonder how it should be enabled in the frontend, where there is hardcoded url https://github.com/oda-hub/frontend-astrooda/blob/564767c82e08207feb60e7ee5c4020f163ec64bf/astrooda.nameresolver.inc#L4

once the `tnr` (transient name resolver / the name resolver) is upgraded with your plugin it will just work.
What is hardcoded is persistent link, only with the API versions.

You are upgrading the `tnr` with this PR, right? I am not sure what is unclear, sorry.

**Comment by volodymyrss** [comment]
> I mean the hostname cdcihn. How is it resolved? Or do I need to explicitly name the service, if I want to use the resolver on external deployment?

It's resolved internally. We could better refer to external endpoint. 

Or you can make your own copy, call it internally cdcihn. This is a bit strange.
