### ISSUE TITLE
check that gw is resolvalbe in staging

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/oda-resolver#8]

**Comment by dsavchenko** [comment]
Doesn't work for me. 

Will add test in https://github.com/oda-hub/oda_test_kit/blob/master/test_resolver.py

**Comment by volodymyrss** [comment]
It's just not connected right. But once the test is there I can track more easily.

**Comment by volodymyrss** [comment]
It works now:

![image.png](https://images.zenhubusercontent.com/607479883b297d34d178c6c2/fdba6384-c8f4-4ef0-bfe5-94930a930609)

I did not notice it was disabled by default:

https://github.com/oda-hub/oda-resolver-chart/blob/901dfd08f361e442ce33d64686f0ff4a7c319f84/templates/deployment.yaml#L37-L38

Also there is a need for patch on deployment due to hard-coded reference. 

https://github.com/oda-hub/frontend-chart/blob/bc1890c53f240cb10ffecf0e8d3cf087162def40/make.sh#L231

**Comment by volodymyrss** [comment]
let's continue there https://github.com/oda-hub/oda_test_kit/issues/7
